---
title: "18477142_MICB425_DSF_Assignment4"
author: "Joshua Bray (18477142)"
date: "February 15, 2018"
output:
  html_document: default
  pdf_document: default
---
#Prep work

```{r}
#Load libraries
library(tidyverse)
library(phyloseq)

#Load Data
metadata = read.table(file="Saanich.metadata.txt", header=TRUE, row.names=1, sep="\t")
load("phyloseq_object.RData")

#Convert Phyloseq data to percent
physeq_percent = transform_sample_counts(physeq, function(x) 100 * x/sum(x))
```

#Exercise 1
```{r}
#SiO2 vs Depth, with purple triangles
ggplot(metadata, aes(x=SiO2_uM, y=Depth_m)) +
  geom_point(color="purple", shape=17)
```
#Exercise 2
```{r}
#Temperature_F vs Depth_m
metadata %>%
  mutate(Temperature_F = Temperature_C*9/5+32) %>% #Convert temperature to F and pipe it to ggplot
    ggplot(aes(x=Temperature_F, y=Depth_m)) +
      geom_point()
```

#Exercise 3
```{r}
plot_bar(physeq_percent, fill="Class") + 
  geom_bar(aes(fill=Class), stat="identity") +
  labs(x="Sample Depth", y="Percent relative abundance")
```

#Exercise 4
```{r}
metadata %>% 
  gather(Nutrient, uM, NH4_uM, NO2_uM, NO3_uM, O2_uM, PO4_uM, SiO2_uM) %>% #Put all the desired data into a single column
  ggplot(aes(x=Depth_m, y=uM))+
  geom_point() +
  geom_line() + #Do both point and lines for the graph
  facet_wrap(~Nutrient, scales="free_y") +
  theme(legend.position="none")
```